### ISSUE TITLE
Meta: Polyfills + Babel helpers

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#248]
Just going to make another issue to talk about the ideal scenario for both polyfills and babel helpers and how we can get there via babel-preset-env.

How can we write ES20xx and ship the smallest amount of code (for a given target environment)?

- [x] syntax: if your target environment supports that syntax, don't compile it (the original point of this project)
- [x] polyfill: if your target environment supports that built-in, don't polyfill it (done in https://github.com/babel/babel-preset-env/issues/20 v1.0.0)
- [x] polyfill: if your code doesn't actually use the polyfill, don't add it (do a pass over all code to find the use of a built-in) https://github.com/babel/babel-preset-env/pull/241
- [ ] bundler: do polyfills need to be it's own chunk (webpack)?
- [ ] babel helpers: reference the same helpers instead of recreating per file (either via https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-runtime#options) or (http://babeljs.io/docs/plugins/external-helpers)
  - [ ] https://github.com/babel/babel-preset-env/issues/246 Move transform-runtime into this preset if a library (`type: "library"`)?
  - [ ] https://github.com/babel/babel-preset-env/issues/247 Move external-helpers into this preset if an application (`type: "app"`)?

**Comment by Kovensky** [comment]
I don't think external-helpers should be a thing if you're going to use a module system; transform-runtime with useBuiltIns should already cover everything without adding an extra global to the application.

If you're going to separate things into libraries and apps, I think that libraries should _only_ use helpers and use the built-ins from the environment. It is up to the app to provide the polyfills if the environment you expect to run on is outdated. If, for some reason, you still want to prevent your app from patching your environment, you can do a transform-runtime pass on all files transforming builtins.

**Comment by rtsao** [comment]
> If you're going to separate things into libraries and apps, I think that libraries should only use helpers and use the built-ins from the environment.

Agreed on polyfills, but I think helpers belong in the libraries themselves. If I'm writing a library that doesn't need polyfills, my library should work out of the box by someone not using Babel.

I propose having a standalone `babel-helpers` package that allows libraries to import individual babel helpers. Then the application can consume the same `babel-helpers` package as used in node_modules, so you have full de-duplication of babel helpers, but the babel helpers are de-duplicated. If the `babel-helpers` package exports an ES Module (via the `module` field of package.json) any unused babel helpers can be tree-shaken.
